# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!

target 'Recording' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recording

end

target 'Sharing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BlueSocket'
#  pod 'Socket.IO-Client-Swift'
  pod 'EFQRCode'

end

target 'Upload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Upload

end

target 'UploadSetupUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UploadSetupUI

end
